### ISSUE TITLE
Crash: Tapping search and scrolling

### ISSUE THREAD

**Issue by StuartMorris0** [ihomam/CollectionViewWithSearchBar#2]
I am testing on simulator, but if you tap in the search field and then begin to try and scroll the collection view the application will crash. I will look further into this, but thought I should report as an issue.

**Comment by ihomam** [comment]
Hi StuartMorris0 
just updated the project and fixed the issue, try it and let me know .. if something came up

**Comment by StuartMorris0** [comment]
Thanks, looks to be the same fix i implemented
