### ISSUE TITLE
UIRefreshControl

### ISSUE THREAD

**Issue by jadar** [ihomam/CollectionViewWithSearchBar#3]
What is the best way to do this with a UIRefreshControl on the UICollectionView? Right now it occupies the same space as the search bar..

![ios simulator screen shot mar 5 2015 5 17 43 pm](https://cloud.githubusercontent.com/assets/3793928/6516896/8d6b93a0-c35b-11e4-9b8c-11cd711f16e1.png)

**Comment by ihomam** [comment]
HI jadar
I updated the project, clone it and check it out 
I added UIRefreshControl support

**Comment by jadar** [comment]
Whoa!! How did you do that?? I was finally able to achieve this with nested scroll views but then I couldn't programaticly scroll to top or tap on status bar and scroll to the top. This fixes all that!

**Comment by ihomam** [comment]
I used UICollectionViewDelegateFlowLayout to update collectionViewContentInset dynamically ;)
